//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Photos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhotoDto", Namespace="http://schemas.datacontract.org/2004/07/Ef_design_first.DTOs", IsReference=true)]
    public partial class PhotoDto : object
    {
        
        private System.DateTime dateField;
        
        private string descriptionField;
        
        private string evenimentField;
        
        private string locationField;
        
        private string pathField;
        
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string eveniment
        {
            get
            {
                return this.evenimentField;
            }
            set
            {
                this.evenimentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonDto", Namespace="http://schemas.datacontract.org/2004/07/Ef_design_first.DTOs", IsReference=true)]
    public partial class PersonDto : object
    {
        
        private string nameField;
        
        private string surnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Photo", Namespace="http://schemas.datacontract.org/2004/07/Ef_design_first", IsReference=true)]
    public partial class Photo : object
    {
        
        private System.DateTime DataField;
        
        private string DescriereField;
        
        private string EvenimentField;
        
        private int IdField;
        
        private Photos.Location LocationField;
        
        private int LocationIdField;
        
        private string OtherField;
        
        private string PathField;
        
        private System.Collections.Generic.List<Photos.Person> PeopleField;
        
        private string TitluField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descriere
        {
            get
            {
                return this.DescriereField;
            }
            set
            {
                this.DescriereField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eveniment
        {
            get
            {
                return this.EvenimentField;
            }
            set
            {
                this.EvenimentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Photos.Location Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId
        {
            get
            {
                return this.LocationIdField;
            }
            set
            {
                this.LocationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Other
        {
            get
            {
                return this.OtherField;
            }
            set
            {
                this.OtherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Photos.Person> People
        {
            get
            {
                return this.PeopleField;
            }
            set
            {
                this.PeopleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titlu
        {
            get
            {
                return this.TitluField;
            }
            set
            {
                this.TitluField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/Ef_design_first", IsReference=true)]
    public partial class Location : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private System.Collections.Generic.List<Photos.Photo> PhotosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Photos.Photo> Photos
        {
            get
            {
                return this.PhotosField;
            }
            set
            {
                this.PhotosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Ef_design_first", IsReference=true)]
    public partial class Person : object
    {
        
        private int IdField;
        
        private string NumeField;
        
        private System.Collections.Generic.List<Photos.Photo> PhotosField;
        
        private string PrenumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nume
        {
            get
            {
                return this.NumeField;
            }
            set
            {
                this.NumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Photos.Photo> Photos
        {
            get
            {
                return this.PhotosField;
            }
            set
            {
                this.PhotosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prenume
        {
            get
            {
                return this.PrenumeField;
            }
            set
            {
                this.PrenumeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Photos.IServiceWCF")]
    public interface IServiceWCF
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/AddPhoto", ReplyAction="http://tempuri.org/IServiceWCF/AddPhotoResponse")]
        System.Threading.Tasks.Task<string> AddPhotoAsync(Photos.PhotoDto photo, string other, System.Collections.Generic.List<Photos.PersonDto> persons);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/GetAll", ReplyAction="http://tempuri.org/IServiceWCF/GetAllResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Photos.Photo>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/GetByTitle", ReplyAction="http://tempuri.org/IServiceWCF/GetByTitleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Photos.Photo>> GetByTitleAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/GetByEvent", ReplyAction="http://tempuri.org/IServiceWCF/GetByEventResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Photos.Photo>> GetByEventAsync(string eveniment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/GetByLocation", ReplyAction="http://tempuri.org/IServiceWCF/GetByLocationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Photos.Photo>> GetByLocationAsync(string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/GetByOther", ReplyAction="http://tempuri.org/IServiceWCF/GetByOtherResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Photos.Photo>> GetByOtherAsync(string other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/modifyTitle", ReplyAction="http://tempuri.org/IServiceWCF/modifyTitleResponse")]
        System.Threading.Tasks.Task modifyTitleAsync(int photoId, string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/modifyEvent", ReplyAction="http://tempuri.org/IServiceWCF/modifyEventResponse")]
        System.Threading.Tasks.Task modifyEventAsync(int photoId, string eveniment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/modifyDescription", ReplyAction="http://tempuri.org/IServiceWCF/modifyDescriptionResponse")]
        System.Threading.Tasks.Task modifyDescriptionAsync(int photoId, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceWCF/modifyOther", ReplyAction="http://tempuri.org/IServiceWCF/modifyOtherResponse")]
        System.Threading.Tasks.Task modifyOtherAsync(int photoId, string others);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceWCFChannel : Photos.IServiceWCF, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceWCFClient : System.ServiceModel.ClientBase<Photos.IServiceWCF>, Photos.IServiceWCF
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceWCFClient() : 
                base(ServiceWCFClient.GetDefaultBinding(), ServiceWCFClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceWCF.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWCFClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceWCFClient.GetBindingForEndpoint(endpointConfiguration), ServiceWCFClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWCFClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceWCFClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWCFClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceWCFClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> AddPhotoAsync(Photos.PhotoDto photo, string other, System.Collections.Generic.List<Photos.PersonDto> persons)
        {
            return base.Channel.AddPhotoAsync(photo, other, persons);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Photos.Photo>> GetAllAsync()
        {
            return base.Channel.GetAllAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Photos.Photo>> GetByTitleAsync(string title)
        {
            return base.Channel.GetByTitleAsync(title);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Photos.Photo>> GetByEventAsync(string eveniment)
        {
            return base.Channel.GetByEventAsync(eveniment);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Photos.Photo>> GetByLocationAsync(string location)
        {
            return base.Channel.GetByLocationAsync(location);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Photos.Photo>> GetByOtherAsync(string other)
        {
            return base.Channel.GetByOtherAsync(other);
        }
        
        public System.Threading.Tasks.Task modifyTitleAsync(int photoId, string title)
        {
            return base.Channel.modifyTitleAsync(photoId, title);
        }
        
        public System.Threading.Tasks.Task modifyEventAsync(int photoId, string eveniment)
        {
            return base.Channel.modifyEventAsync(photoId, eveniment);
        }
        
        public System.Threading.Tasks.Task modifyDescriptionAsync(int photoId, string description)
        {
            return base.Channel.modifyDescriptionAsync(photoId, description);
        }
        
        public System.Threading.Tasks.Task modifyOtherAsync(int photoId, string others)
        {
            return base.Channel.modifyOtherAsync(photoId, others);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceWCF))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceWCF))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8000/PC");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceWCFClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceWCF);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceWCFClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceWCF);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceWCF,
        }
    }
}
